### ISSUE TITLE
[Question] `@DataJpaTest` 보다 `@SpringBootTest`를 선호하는 이유?

### ISSUE THREAD

**Issue by JadeKim042386** [Keep-Going-Web-Study/BE-Spring-Test-Guide#9]
## 질문 내용

Persistence Layer 강의 중에서 `@DataJpaTest` 보다 `@SpringBootTest`를 선호한다고 말하는데요. 이유를 강사가 말해주었나요? 어디서 말했는지 찾을 수가 없네요.

**Comment by JisuPark-dev** [comment]
dataJpa의 경우에 내부적으로 Transactional을 포함하고 있어서, service로직에서 transactional이 보장되지 못했을 경우를 잡아내지 못하는 문제점이 있는 것 같아요.

**Comment by JisuPark-dev** [comment]
덧붙여서 @dataJpa를 사용할 경우, 
@DataJpaTest
class TestUsingDataJpaTest {
    @Autowired
    private MemberRepository memberRepository;

    @Test
    void contextLoads() {
        Member member = new Member();
        member.setAge(10);
        member.setName("fdsafdsafa");
        memberRepository.save(member);
    }

}
다음과 같은 테스트에서는 insertQuery가 나가지 않을 수 있다고 하는데요, 이유는 Jpa는 쿼리를 바로 날리는 것이 아니라, 영속성 컨텍스트에 쿼리를 저장해놨다가, flush시점에 쿼리를 한번에 보내기 때문입니다. 그래서 만약 flush이전에 rollback을 하게 된다면 insert쿼리가 나가지 않게 된다고 합니다.

반면 SpringBootTest + @AfterEach 조합을 사용할 경우에는 Transactional 어노테이션이 없어서 모든 쿼리를 로그에서 롤백과 상관없이 볼 수있을 것같아요.

**Comment by eod940** [comment]
참고자료까지 있어서 쉽게 이해할 수 있었습니다 감사합니다 😄

**Comment by JisuPark-dev** [comment]
SpringBootTest는 모든 Bean을 가져와야해서 무겁다는 단점이있습니다.

**Comment by JadeKim042386** [comment]
`@Rollback(value = false)`을 사용하면 롤백이 안되도록 적용할 수 있습니다. (by 유석균님)

**Comment by JisuPark-dev** [comment]
@Transactional 어노테이션은 그럼 언제 롤백되는 걸까요?

**Comment by je-pa** [comment]
요고 궁금해서 직접 작성해봤는데 insert 쿼리문 날아가더라고요.
```java
@ActiveProfiles("test")
@DataJpaTest
class SaveTest {
  @Autowired
  private ProductRepository productRepository;

  @Test
   void createOrderWithNoStock() {
    // given
    Product product1 = createProduct(BOTTLE, "001", 1000);
    productRepository.save(product1);
  }

  private Product createProduct(ProductType type, String productNumber, int price) {
    return Product.builder()
        .type(type)
        .productNumber(productNumber)
        .price(price)
        .sellingStatus(SELLING)
        .name("메뉴 이름")
        .build();
  }

}
```
아래는 실행결과 중 일부 입니다.
```sql
2024-06-18T21:58:30.747+09:00  INFO 10272 --- [    Test worker] s.c.spring.api.service.order.Test        : Started Test in 3.695 seconds (process running for 4.852)
Hibernate: 
    insert 
    into
        product
        (created_date_time, modified_date_time, name, price, product_number, selling_status, type, id) 
    values
        (?, ?, ?, ?, ?, ?, ?, default)
```
save 자체에 transactional이 있어서 save 메서드가 끝나는 시점에 insert 쿼리문은 날라갈 것 같은데 
블로그에서 콘솔에 쿼리가 찍히지 않았다는건 application.yml 같은 설정을 덜 적어 놓았거나 그런게 아닐까 싶네요..

**Comment by je-pa** [comment]
@JisuPark-dev @transactional 롤백은 JUnit을 통한 Test가 실행된다면 @Transactional이 적용되어있는 로직이 끝나는 시점에 롤백이 된다는 것 같습니다.

**Comment by je-pa** [comment]
@JadeKim042386  요고 제가 강의 들으면서 필기한 내용인데 도움이 되셨으면 좋겠습니다!

> `@Transactional`을 사용하면 실제 테스트 하고자하는 로직에 `@Transactional`을 적용하지 않았음에도 적용한 것 처럼 작동한다.
> 
> 때문에 `@Transactional`적용해야 할 곳에 적용이 되지 않았어도 테스트가 성공해버려서 검증이 제대로 이루어지지 않기 때문에 주의가 필요하다.

**Comment by JadeKim042386** [comment]
@je-pa 위에서 insert 쿼리 실행하신 결과를 확인했는데요. 

hibernate 쿼리 로그로는 확인하신 것처럼 insert 쿼리가 출력되는 것을 볼 수 있으시지만, orm.jpa의 debug 레벨로 확인해보시면 insert 쿼리가 수행된 이후 바로 롤백이 되는 것을 확인 하실 수 있습니다.

jdbc 레벨에서의 로그까지 확인해보면 다음과 같습니다. (조금 기네요;;)

```
2024-06-19 00:05:19.907 DEBUG 20841 --- [           main] o.s.orm.jpa.JpaTransactionManager        : Creating new transaction with name [sample.cafekiosk.spring.domain.product.ProductRepositoryTest.save]: PROPAGATION_REQUIRED,ISOLATION_DEFAULT
2024-06-19 00:05:19.908 DEBUG 20841 --- [           main] o.s.orm.jpa.JpaTransactionManager        : Opened new EntityManager [SessionImpl(77567832<open>)] for JPA transaction
2024-06-19 00:05:19.908  INFO 20841 --- [           main] MySQL                                    : [QUERY] SET autocommit=0 [Created on: Wed Jun 19 00:05:19 KST 2024, duration: 0, connection-id: 41, statement-id: -1, resultset-id: 0,	at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:414)]
2024-06-19 00:05:19.908  INFO 20841 --- [           main] MySQL                                    : [FETCH]  [Created on: Wed Jun 19 00:05:19 KST 2024, duration: 0, connection-id: 41, statement-id: -1, resultset-id: 0,	at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:414)]
2024-06-19 00:05:19.909 DEBUG 20841 --- [           main] o.s.orm.jpa.JpaTransactionManager        : Exposing JPA transaction as JDBC [org.springframework.orm.jpa.vendor.HibernateJpaDialect$HibernateConnectionHandle@77acc95a]
2024-06-19 00:05:19.909  INFO 20841 --- [           main] o.s.t.c.transaction.TransactionContext   : Began transaction (1) for test context [DefaultTestContext@1c9b0314 testClass = ProductRepositoryTest, testInstance = sample.cafekiosk.spring.domain.product.ProductRepositoryTest@ff1a5a0, testMethod = save@ProductRepositoryTest, testException = [null], mergedContextConfiguration = [MergedContextConfiguration@45385f75 testClass = ProductRepositoryTest, locations = '{}', classes = '{class sample.cafekiosk.spring.CafekioskApplication}', contextInitializerClasses = '[]', activeProfiles = '{test}', propertySourceLocations = '{}', propertySourceProperties = '{org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTestContextBootstrapper=true}', contextCustomizers = set[org.springframework.boot.test.autoconfigure.OverrideAutoConfigurationContextCustomizerFactory$DisableAutoConfigurationContextCustomizer@4da4253, org.springframework.boot.test.autoconfigure.actuate.metrics.MetricsExportContextCustomizerFactory$DisableMetricExportContextCustomizer@2abf4075, org.springframework.boot.test.autoconfigure.filter.TypeExcludeFiltersContextCustomizer@351584c0, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@cb246fc0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@693fe6c9, [ImportsContextCustomizer@49c90a9c key = [org.springframework.boot.autoconfigure.transaction.TransactionAutoConfiguration, org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManagerAutoConfiguration, org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, org.springframework.boot.autoconfigure.sql.init.SqlInitializationAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration, org.springframework.boot.test.autoconfigure.jdbc.TestDatabaseAutoConfiguration, org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration, org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration]], org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@7e7be63f, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@4738a206, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.context.SpringBootTestArgs@1, org.springframework.boot.test.context.SpringBootTestWebEnvironment@0], contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]], attributes = map['org.springframework.test.context.event.ApplicationEventsTestExecutionListener.recordApplicationEvents' -> false]]; transaction manager [org.springframework.orm.jpa.JpaTransactionManager@4148ce43]; rollback [true]
2024-06-19 00:05:19.909 DEBUG 20841 --- [           main] o.s.orm.jpa.JpaTransactionManager        : Found thread-bound EntityManager [SessionImpl(77567832<open>)] for JPA transaction
2024-06-19 00:05:19.909 DEBUG 20841 --- [           main] o.s.orm.jpa.JpaTransactionManager        : Participating in existing transaction
Hibernate: 
    insert 
    into
        product
        (created_date_time, modified_date_time, name, price, product_number, selling_status, type) 
    values
        (?, ?, ?, ?, ?, ?, ?)
2024-06-19 00:05:19.915  INFO 20841 --- [           main] MySQL                                    : [QUERY] insert into product (created_date_time, modified_date_time, name, price, product_number, selling_status, type) values ('2024-06-19 00:05:19.910086', '2024-06-19 00:05:19.910086', '아메리카노', 4000, '001', 'SELLING', 'HANDMADE') [Created on: Wed Jun 19 00:05:19 KST 2024, duration: 1, connection-id: 41, statement-id: 0, resultset-id: 0,	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)]
2024-06-19 00:05:19.916  INFO 20841 --- [           main] MySQL                                    : [FETCH]  [Created on: Wed Jun 19 00:05:19 KST 2024, duration: 0, connection-id: 41, statement-id: 0, resultset-id: 0,	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)]
2024-06-19 00:05:19.918 DEBUG 20841 --- [           main] o.s.orm.jpa.JpaTransactionManager        : Initiating transaction rollback
2024-06-19 00:05:19.918 DEBUG 20841 --- [           main] o.s.orm.jpa.JpaTransactionManager        : Rolling back JPA transaction on EntityManager [SessionImpl(77567832<open>)]
2024-06-19 00:05:19.919  INFO 20841 --- [           main] MySQL                                    : [QUERY] rollback [Created on: Wed Jun 19 00:05:19 KST 2024, duration: 1, connection-id: 41, statement-id: -1, resultset-id: 0,	at com.zaxxer.hikari.pool.ProxyConnection.rollback(ProxyConnection.java:396)]
2024-06-19 00:05:19.919  INFO 20841 --- [           main] MySQL                                    : [FETCH]  [Created on: Wed Jun 19 00:05:19 KST 2024, duration: 0, connection-id: 41, statement-id: -1, resultset-id: 0,	at com.zaxxer.hikari.pool.ProxyConnection.rollback(ProxyConnection.java:396)]
2024-06-19 00:05:19.920  INFO 20841 --- [           main] MySQL                                    : [QUERY] SET autocommit=1 [Created on: Wed Jun 19 00:05:19 KST 2024, duration: 0, connection-id: 41, statement-id: -1, resultset-id: 0,	at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:414)]
2024-06-19 00:05:19.920  INFO 20841 --- [           main] MySQL                                    : [FETCH]  [Created on: Wed Jun 19 00:05:19 KST 2024, duration: 1, connection-id: 41, statement-id: -1, resultset-id: 0,	at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:414)]

```

**Comment by JadeKim042386** [comment]
추가로 `saveAndFlush`를 해도 똑같이 롤백되는 것은 마찬가지였습니다. (`@DataJpaTest` 들어가보니까 `@Transactional`이 적용되어있었네요.)

**Comment by je-pa** [comment]
@JadeKim042386  넵 롤백은 되는데 
> 다음과 같은 테스트에서는 insertQuery가 나가지 않을 수 있다고 하는데요 
라고 하셔서 쿼리문은 날아간다는 말이었습니다!
블로그에서도 
> 하지만 같은코드를@DataJpaTest를 이용하여 실행하면 insert query가 실행되지 않는 것을 확인할 수 있습니다.
라고 작성되어 있어서 이부분 정정한 것입니다!

JUnit을 통한 Test가 실행된다면 `@Transactional`이 적용되어있는 로직이 끝나는 시점에 롤백이 되기 때문에
`@Transactional`이 적용되어있는 `@DataJpaTest`를 통해 test를 작성한다면 롤백이 되는 것이 맞습니다. 다만 insert query가 실행되지 않는다는 것은 아니지 않나라고 생각했습니다.

**Comment by JadeKim042386** [comment]
@je-pa 아! 약간 오해가 있었네요 ㅎㅎ 말씀해주셔서 감사합니다.
